# Generated by Django 3.1 on 2020-08-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200827_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imageee',
            new_name='image',
        ),
    ]
