# Generated by Django 3.1 on 2020-08-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200830_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
